---
title: "R Notebook"
output: html_notebook
---
Read in data and plot one or more temp sensors, filter by dates

```{r}
library(ggplot2)
library(tidyverse)
library(lubridate)
```


```{r}

locations <- read_csv("Sensor Locations.csv")
setwd("G:/My Drive/Independent Study Fall 2020/McDonald_Hollow/Corrected Temperature Files")
tempdata <-
    list.files(pattern = "*.csv") %>% 
    map_dfr(~read_csv(.) %>% 
              mutate(Sensor = .x)) %>%
    mutate_at("Sensor", str_trunc, width = 10, side='right', ellipsis = '') %>%
    mutate_at("Sensor", str_replace_all, pattern = ' ', replacement = '')
tempdata <- left_join(tempdata, locations, by = c("Sensor" = "SensorID"))

```


```{r}

toplot <- filter(tempdata, Sensor == "SN20680147")

ggplot(toplot, aes(DateTime, TempCor_F))+
  geom_line()+
  labs(title = "Sensor SN20680147- Air", x = "Time", y = "Temperature")+
  theme_bw()

```

PIVOT DATA WIDE 
```{r}

pivot_wider(tempdata, names_from = Sensor, values_from = TempCor_F, DateTime)

```


PIVOT DATA LONG AND CREATE COLUMN THAT DETERMINES FLOW PRESENCE
```{r}

```

