---
title: "R Notebook"
output: html_notebook
---

## Create daily summaries

```{r}
#daily summaries for sensor temperature - water temperature
dailysummaries <- subMS8L %>% 
  group_by(Name, 
           year = year(DateTime), 
           month = month(DateTime), 
           day =  day(DateTime)) %>%
  summarise(meandt = mean(TempFsub, na.rm = TRUE), sddt = sd(TempFsub, na.rm = TRUE),
            maxdt = max(TempFsub, na.rm = TRUE), mindt = min(TempFsub, na.rm = TRUE), lengthData = length(TempFsub)) %>%
  mutate(date = mdy(paste(month, day, year))) %>%
  ungroup() %>%
  select(!c(month, year, day)) 

#add reference AIR and WATER values to whole dataset
AIR <- filter(dailysummaries, Name == "MS8_Air") %>%
  rename(meandt_AIR = meandt,
         sddt_AIR = sddt,
         maxdt_AIR = maxdt,
         mindt_AIR = mindt) %>%
  select(!Name)
  
WATER <- filter(dailysummaries, Name == "MS8")%>%
  rename(meandt_WATER = meandt,
         sddt_WATER = sddt,
         maxdt_WATER = maxdt,
         mindt_WATER = mindt) %>%
  select(!Name)

dailysummaries <- dailysummaries %>%
  left_join(AIR, by = "date") %>%
  left_join(WATER, by = "date")
  
```

## test plots

```{r}
sites <- c("MS2", "MS6", "MS7")

dailysummaries %>% filter(Name %in% sites) %>%
  ggplot(aes(date, sddt, color = Name))+
  geom_line()
```

## Determine a way to apply a filter to data and say which is in water or not

```{r}
#if standard deviation of difference from water temp (sddt) is 
#less than 15% of the sddt of a known air sensor (MS8_air), it is in water
submerged1 <- dailysummaries %>%
  mutate(inWater = case_when(
                    sddt < (0.25 * sddt_AIR) ~ 1,
                    sddt >= (0.25 * sddt_AIR) ~ 0
                   ))%>%
  mutate(outdate=paste0("D", month(date), day(date), year(date)))


```

## Test plots

```{r}
airsensors <- c("MS8_Air","MS13_Air","TRIB2_1_Air","MS19_Air","MS2_Air")
nonairsensors <- c("MS3", "MS4", "MS5", "MS6", "MS7", "MS8", "MS9", "MS10", "MS11", "MS12", "MS13", "MS14", "MS15", "MS16", "MS17", "MS18", "MS19", "MS20", "MS21", "TRIB1", "TRIB2_1", "TRIB2_2", "TRIB2_3", "TRIB3")

#submerged1 %>% filter(Name %in% nonairsensors)%>%
  #ggplot(aes(x = date, y = as.factor(Name), fill = as.factor(inWater), scale = "free_y", space = "free"))+
  #geom_tile(color = "black")+
  #theme_linedraw()+
  #ylab(element_blank())+
  #xlab(element_blank())

p2 <- submerged1 %>% filter(Name %in% nonairsensors)%>%
  ggplot(aes(x = date, y = factor(Name, levels = c("MS1", "TRIB1", "MS2", "MS3", "MS4", "MS5", "MS6", "MS7", "MS8", "MS9", "MS10", "MS11", "MS12", "MS13", "TRIB2_1", "TRIB2_2", "TRIB2_3", "MS14", "MS15", "MS16", "MS17", "MS18", "TRIB3", "MS19", "MS20", "MS21")), fill = as.factor(inWater)))+
  geom_tile(color = "black")+
  theme_linedraw()+
  ylab(element_blank())+
  xlab(element_blank())
 
#setwd("G:/My Drive/Independent Study Fall 2020/McDonald_Hollow/McDonald_Hollow_Wet_Dry_Maps/wet and dry days")
#ggsave("heatmap.pdf", device="pdf")
#ggsave("heatmap.jpg", device="jpg")

#1 (blue) = water & 0 (red) = air
  
```


```{r}
dailysummaries%>%
  ggplot(aes(x = date, y = Name, fill = as.factor(lengthData)))+
  geom_tile(color = "black")+
  theme_linedraw()
```

```{r}
#pivot data to make it easy to switch dates in arcgispro
wetdrywide <- submerged1%>%
  pivot_wider(id_cols = Name, outdate, values_from = inWater)

#wetdrylong <- wetdrywide%>%
  #pivot_longer(!date, names_to = "Name", values_to = "inWater")
wetdry <- right_join(wetdrywide, locations, by = c("Name" = "Name"))

wetdrysep <- select(wetdry, Name, matches("D882020"))
setwd("G:/My Drive/Independent Study Fall 2020/McDonald_Hollow")
#write.csv(wetdry,"wetdry.csv")


```


```{r}
library(patchwork)

setwd("G:/My Drive/Independent Study Fall 2020/McDonald_Hollow")
stage <- read_csv("Copy of McDonald_Hollow_MonStat_Data_Jan21.csv", col_types = "Tddddddddddd")
blue <- c("09-25-2020")
red <- c("08-12-2020")

p1 <- stage %>% filter(datetime > mdy("08-05-2020") & datetime < mdy("01-14-2021"))%>%
    ggplot(aes(datetime, Stage_m_pt))+
    geom_line()+
    ylab("Stream stage (m)")+
    xlab(element_blank())+
    geom_vline(aes(xintercept = as_datetime(c("2020-09-25")), color = blue))+
    geom_vline(aes(xintercept = as_datetime(c("2020-08-12")), color = red))+
  theme_classic()
  
  

p1 / p2
#ggsave("heatmap.jpg", device="jpg")



```











