---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
library(dplyr)
```

```{r}

locations <- read_csv("Sensor Locations.csv")
#setwd("~/Google Drive File Stream/My Drive/Brush Mtn Station/Temp sensors/CurrentTempData_15Jan2021")
setwd("G:/My Drive/Independent Study Fall 2020/McDonald_Hollow/CurrentTempData_15Jan2021")
tempdata <-
    list.files(pattern = "*.csv") %>% 
    map_dfr(~read_csv(.) %>% 
              mutate(Sensor = .x)) %>%
    mutate_at("Sensor", str_trunc, width = 10, side='right', ellipsis = '') %>%
    mutate_at("Sensor", str_replace_all, pattern = ' ', replacement = '')
tempdata <- left_join(tempdata, locations, by = c("Sensor" = "SensorID"))%>%
  drop_na()%>%
  filter(DateTime < mdy_hms("11-01-2020 01:00:00") | DateTime > mdy_hms("11-01-2020 02:00:00")) #cuts out daylight savings weirdness.... need permanent fix
```
```{r}
#plot an individual sensor
toplot <- filter(tempdata, Name == "MS8")
ggplot(toplot, aes(DateTime, TempCor_F))+
  geom_line()+
  labs(title = "Mainstem In-Stream Sensor (MS8)", x = "Time", y = "Temperature")+
  theme_bw()
```

```{r}
#pivot data wide
wide <- pivot_wider(tempdata, names_from = Name, values_from = TempCor_F, DateTime)

#SUBAIR (every MS sensor - sensor in the air)
#function that subtracts the sensor you want from whatever is passed to it
subair <- function(x, na.rm = FALSE) (x - wide$MS8_Air)

#New tibble with sensor in subair function subtracted from all sensors
subMS8_Air <- wide %>% mutate_at(vars(matches("MS")), subair)

#new tibble in long format, joined with location data
subMS8_AirL <- subMS8_Air %>% pivot_longer(!DateTime, names_to = "Name", values_to = "TempFsub")%>%
  left_join(locations, by = c("Name" = "Name"))


#SUBWATER (every MS sensor - sensor in the water)
#function that subtracts the sensor you want from whatever is passed to it
subwater <- function(x, na.rm = FALSE) (x - wide$MS8)

#New tibble with sensor in subair function subtracted from all sensors
subMS8 <- wide %>% mutate_at(vars(matches("MS")), subwater)

#new tibble in long format, joined with location data
subMS8L <- subMS8 %>% pivot_longer(!DateTime, names_to = "Name", values_to = "TempFsub")  %>%
  left_join(locations, by = c("Name" = "Name"))
```


```{r}
#SUB AIR
#plot a bunch of sensors and color by location
subMS8_AirL %>% filter(Type == "Stream", Stream == "MS")%>%
ggplot(aes(DateTime, TempFsub, color = Name))+
  geom_line()+
  labs(title = "Mainstem in-stream sensors", x = "Time", y = "Temperature")

```

```{r}
#SUB WATER
sites <- c("MS6", "MS7", "MS8", "MS9", "MS10", "MS11", "MS12")
subMS8L %>% filter(Name %in% sites)%>%
ggplot(aes(DateTime, TempFsub, color = Name))+
  geom_line()+
  labs(title = "Mainstem in-stream sensors", x = "Time", y = "Temperature")
```


```{r}
#plot smaller groups
tempdata%>% filter(Name == c("MS1", "MS2", "TRIB1"), between(DateTime, as_datetime("2020-09-15 13:30:00"), as_datetime("2020-10-01 13:30:00")))%>%
ggplot(aes(DateTime, TempCor_F, color = Name))+
  geom_line()+
  labs(title = "MS1, MS2, TRIB1 Sensors", x = "Time", y = "Temperature")+
  theme_bw()

#, between(DateTime, as_datetime("2020-08-15 13:30:00"), as_datetime("2020-09-01 13:30:00"))
```

```{r}
#plot smaller groups
tempdata%>% filter(Name == c("MS4", "MS5"))%>%
ggplot(aes(DateTime, TempCor_F, color = Name))+
  geom_line()+
  labs(title = "MS 4 and 5 Sensors", x = "Time", y = "Temperature")+
  theme_bw()

#, between(DateTime, as_datetime("2020-08-15 13:30:00"), as_datetime("2020-09-01 13:30:00"))
```



```{r}
#plot smaller groups
tempdata%>% filter(Name == c("MS6", "MS7", "MS8", "MS9", "MS10", "MS11", "MS12"), between(DateTime, as_datetime("2020-08-15 13:30:00"), as_datetime("2020-09-01 13:30:00")))%>%
ggplot(aes(DateTime, TempCor_F, color = Name))+
  geom_line()+
  labs(title = "MS 6-12 Sensors", x = "Time", y = "Temperature")+
  theme_bw()


#, between(DateTime, as_datetime("2020-08-15 13:30:00"), as_datetime("2020-09-01 13:30:00"))
```


```{r}
#plot smaller groups
tempdata%>% filter(Name == c("MS13", "MS13_Air", "MS13_2"))%>%
ggplot(aes(DateTime, TempCor_F, color = Name))+
  geom_line()+
  labs(title = "MS13 Sensors", x = "Time", y = "Temperature")+
  theme_bw()

#, between(DateTime, as_datetime("2020-08-15 13:30:00"), as_datetime("2020-09-01 13:30:00"))
```

```{r}
#plot smaller groups
tempdata%>% filter(Name == c("MS14", "MS15"), between(DateTime, as_datetime("2020-08-15 13:30:00"), as_datetime("2020-09-01 13:30:00")))%>%
ggplot(aes(DateTime, TempCor_F, color = Name))+
  geom_line()+
  labs(title = "MS 14 and 15 Sensors", x = "Time", y = "Temperature")+
  theme_bw()

#, between(DateTime, as_datetime("2020-08-15 13:30:00"), as_datetime("2020-09-01 13:30:00"))
```

```{r}
#plot smaller groups
tempdata%>% filter(Name == c("MS18", "MS19", "MS19_Air"), between(DateTime, as_datetime("2020-08-15 13:30:00"), as_datetime("2020-09-01 13:30:00")))%>%
ggplot(aes(DateTime, TempCor_F, color = Name))+
  geom_line()+
  labs(title = "MS 18 and 19 Sensors", x = "Time", y = "Temperature")+
  theme_bw()

#
```